conky.config = {
    alignment = 'top_left',
    gap_x = 18,
    gap_y = 22,

    update_interval = 1,
    total_run_times = 0,

    use_xft = true,
    xftalpha = 1.0,
    font = 'Rubik:size=9',
    override_utf8_locale = true,

    double_buffer = true,
    text_buffer_size = 8192,

    own_window = true,
    own_window_type = 'dock',
    own_window_title = 'XWeather',
    own_window_class = 'XWeather',
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
    own_window_transparent = true,
    own_window_argb_visual = true,
    own_window_argb_value = 0,

    draw_shades = false,
    draw_borders = false,
    border_width = 0,

    minimum_width = 330,
    maximum_width = 330,
    minimum_height = 570,

    background = false,
};

conky.text = [[
${image ./xweather_glass_panel.png -p 0,0 -s 330x570}
${execpi 900 ./run.sh}
]]
